### ISSUE TITLE
how to solve the equation of the line "Ax + By + C = 0" in this library

### ISSUE THREAD

**Issue by insinfo** [dbforge/SharpMath#9]
how to solve the equation of the line "y = (-C - Ax) / B" in this library

```dart
var A = 1.3333333333333333;
var B = -1;
var C = 0.3333333333333335;

//y = (-C - Ax) / B
//Y = (-0.3333333333333335 - 1.3333333333333333 * X) / -1

```

**Comment by dbforge** [comment]
Transform your equations into linear combinations that result in a number on the other side. E.g. `ax + by = -c`.

The transformation process is not available through this library as it can only handle linear combination inputs suitable for matrix representation so that they can be solved by Gauss. You need to do them yourself based on your inputs prior to handing them over to an instance of `LinearEquation` with the `coefficients` `a` and `b` from the left side and the `result` `-c` on the right side.

Either way, your sole equation is not (uniquely) solvable due to one lacking equation which would result in an exception.
